[project]
name = 'Blockchain-Based-Specialized-Assistive-Device-Customization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.customization-tracking]
path = 'contracts/customization-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.design-sharing]
path = 'contracts/design-sharing.clar'
clarity_version = 2
epoch = 2.5

[contracts.device-registration]
path = 'contracts/device-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
